/*
    Example source code for "Client/Server Connection"

    Copyright © 2016, The Network Protocol Company, Inc.
    
    All rights reserved.

    Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

        1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

        2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer 
           in the documentation and/or other materials provided with the distribution.

        3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived 
           from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
    SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
    SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
    WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
    USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#define PROTOCOL2_IMPLEMENTATION
#define NETWORK2_IMPLEMENTATION

#include "network2.h"
#include "protocol2.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

//const uint32_t ProtocolId = 0x12341651;

const int MaxClients = 32;
//const int ServerPort = 50000;
const int ClientPort = 60000;
const int ChallengeHashSize = 1031;           // IMPORTANT: keep this prime
/*
const float ConnectionTimeOut = 5.0f;
const float ChallengeTimeOut = 10.0f;
const float KeepAliveRate = 1.0f;
*/

uint64_t GenerateSalt()
{
    return ( ( uint64_t( rand() ) <<  0 ) & 0x000000000000FFFFull ) | 
           ( ( uint64_t( rand() ) << 16 ) & 0x00000000FFFF0000ull ) | 
           ( ( uint64_t( rand() ) << 32 ) & 0x0000FFFF00000000ull ) |
           ( ( uint64_t( rand() ) << 48 ) & 0xFFFF000000000000ull );
}

enum PacketTypes
{
    PACKET_CONNECTION_REQUEST,                      // client is requests a connection.
    PACKET_CONNECTION_DENIED,                       // server denies client connection request with reason, eg. "game is full" etc.
    PACKET_CONNECTION_CHALLENGE,                    // server response to client connection request.
    PACKET_CONNECTION_CHALLENGE_RESPONSE,           // client response to server connection challenge.
    PACKET_CONNECTION_KEEP_ALIVE,                   // keep alive packet sent at some low rate (once per-second) to keep the connection alive
    PACKET_CONNECTION_DISCONNECTED,                 // courtesy packet to indicate that the client has been disconnected. better than a timeout
    NUM_CLIENT_SERVER_NUM_PACKETS
};

struct ConnectionRequestPacket : public protocol2::Packet
{
    uint64_t client_salt;
    uint8_t data[256];

    ConnectionRequestPacket() : Packet( PACKET_CONNECTION_REQUEST )
    {
        client_salt = 0;
        memset( data, 0, sizeof( data ) );
    }

    template <typename Stream> bool Serialize( Stream & stream )
    {
        serialize_uint64( stream, client_salt );
        if ( Stream::IsReading && stream.GetBitsRemaining() < 256 * 8 )
            return false;
        serialize_bytes( stream, data, 256 );
        return true;
    }

    PROTOCOL2_DECLARE_VIRTUAL_SERIALIZE_FUNCTIONS();
};

struct ServerChallengeEntry
{
    uint64_t client_salt;                           // random number generated by client and sent to server in connection request
    uint64_t server_salt;                           // random number generated by server and sent back to client in challenge packet
    double last_packet_send_time;                   // the last time we sent a challenge packet to this client
    network2::Address client_address;               // address of the client
};

uint64_t CalculateChallengeHash( const network2::Address & address, uint64_t client_salt )
{
    char buffer[256];
    const char * address_string = address.ToString( buffer, sizeof( buffer ) );
    const int address_length = strlen( address_string );
    return protocol2::murmur_hash_64( &client_salt, 8, protocol2::murmur_hash_64( address_string, address_length, 0 ) );
}

class Server
{
    int num_connected_clients;                                      // number of connected clients
    
    bool client_connected[MaxClients];                              // true if client n is connected
    
    uint64_t client_salt[MaxClients];                               // array of client salt values per-client
    
    uint64_t server_salt[MaxClients];                               // array of server salt values per-client
    
    network2::Address client_address[MaxClients];                   // array of client address values per-client
    
    double client_last_packet_receive_time[MaxClients];             // last time a packet was received from a client (used for timeouts)

    ServerChallengeEntry challenge_entry[ChallengeHashSize];        // challenge hash entries. used to remember client challenge/response before connection

protected:

    void ResetClientState( int client_index )
    {
        assert( client_index >= 0 );
        assert( client_index < MaxClients );
        client_connected[client_index] = false;
        client_salt[client_index] = 0;
        server_salt[client_index] = 0;
        client_address[client_index] = network2::Address();
        client_last_packet_receive_time[client_index] = -1000.0;            // IMPORTANT: avoid bad behavior near t=0.0
    }

    void AddClient( int client_index, const network2::Address & address, uint64_t client_salt, uint64_t server_salt )
    {
        assert( num_connected_clients >= 0 );
        assert( num_connected_clients < MaxClients - 1 );
        assert( !client_connected[client_index] );
        num_connected_clients++;
        client_connected[client_index] = true;
        this->client_salt[client_index] = client_salt;
        this->server_salt[client_index] = server_salt;
    }

public:

    Server()
    {
        num_connected_clients = 0;
        for ( int i = 0; i < MaxClients; ++i )
            ResetClientState( i );
        memset( challenge_entry, 0, sizeof( challenge_entry ) );
    }

    void ProcessConnectionRequest( const ConnectionRequestPacket & packet, const network2::Address & from )
    {
        char buffer[256];
        
        const char *address_string = from.ToString( buffer, sizeof( buffer ) );
        
        uint64_t challenge_hash = CalculateChallengeHash( from, packet.client_salt );
        
        const int challenge_index = challenge_hash % ChallengeHashSize;
        
        printf( "processing connection request packet from: %s\n", address_string );
        printf( "client_salt = %llx\n", packet.client_salt );
        printf( "challenge_hash = %llx\n", challenge_hash );
        printf( "challenge_index = %d\n", challenge_index );

        if ( num_connected_clients == MaxClients )
        {
            printf( "server is full\n" );
            // todo: respond with connection denied packet (tiny)
            return;
        }

        
    }
};

enum ClientState
{
    CLIENT_STATE_DISCONNECTED,
    CLIENT_STATE_SENDING_CONNECTION_REQUEST,
    CLIENT_STATE_SENDING_CHALLENGE_RESPONSE,
    CLIENT_STATE_CONNECTED,
};

struct Client
{
    network2::Address server_address;
    uint64_t server_guid;
    uint64_t client_guid;
};

int main()
{
    srand( (unsigned int) time( NULL ) );

    printf( "client/server connection\n" );

    for ( int i = 0; i < 1; ++i )
    {
        ConnectionRequestPacket packet;
        packet.client_salt = GenerateSalt();
        network2::Address from( "::1", ClientPort + i );

        Server server;
        server.ProcessConnectionRequest( packet, from );
    }

    return 0;
}
